### ISSUE TITLE
Fast forward mode

### ISSUE THREAD

**Issue by ferranpujolcamins** [itadinanta/rust-oids#3]
Here's an idea: 

When on FFW mode, no graphics are rendered so all the cpu can be used to make the simulation advance on time as fast as possible.

**Comment by norru** [comment]
You have been reading my mind. I've impemented it in the last couple of weeks, check it out from the ```develop``` branch.

There is an option to run the simulation in headless mode (-t) and another interactive option to speed up/slow down when graphics are enabled.

**Comment by norru** [comment]
Not quite documented though. ```cargo run --release -- -t``` for the headless mode. It will save gene pools automatically every 5 minutes (so you can recover and run the simulation with graphical feedback).

**Comment by norru** [comment]
Actually, now that I'm re-reading your comment, are you asking for the ability of switching to "headless" mode interactively?

**Comment by ferranpujolcamins** [comment]
Hello, yes that is what I meant. But the actual behaviour in develop is
enough for me. Thank you!

**Comment by norru** [comment]
I'll leave this open, I might implement your suggestion at some point, doesn't sound a bad idea.

**Comment by norru** [comment]
I have added a 100x speedup with no sound - which is basically what you're asking for here.
