### ISSUE TITLE
Error, you program isnt working at all wake up

### ISSUE THREAD

**Issue by Active000** [itadinanta/rust-oids#4]
error[E0432]: unresolved import `libc::sched_param`

.cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.1.0/src/lib.rs:35:9

**Comment by norru** [comment]
Dunno, mate, works on my machine ;)

**Comment by norru** [comment]
Seriously, what platform are you building on? Care to post more details, say at least the output of your `cargo build`?

**Comment by norru** [comment]
Not all plaftorms supported: https://github.com/vityafx/thread-priority

**Comment by norru** [comment]
Closing for lack of feedback.
